name: Build Spring Boot App and Push to GHCR

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${{ secrets.POSTGRES_DB }}
  SPRING_DATASOURCE_USERNAME: ${{ secrets.POSTGRES_USER }}
  SPRING_DATASOURCE_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}

jobs:
  build-wsl:
    name: Build JAR for WSL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Build JAR
        run: mvn clean package -DskipTests

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: tasklist-jar
          path: target/*.jar

  build-docker:
    name: Build and Push Docker image
    runs-on: ubuntu-latest
    needs: build-wsl
    permissions:
      contents: read
      packages: write  # Required to push to GHCR
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Build version tag
      - name: Set image tags
        id: vars
        run: |
          echo "sha_tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          echo "ghcr_image=ghcr.io/${{ github.repository_owner }}/tasklist" >> $GITHUB_OUTPUT
          echo "dockerhub_image=carloslevi/tasklist" >> $GITHUB_OUTPUT

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build \
            --build-arg SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }} \
            --build-arg SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }} \
            --build-arg SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }} \
            --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
            --build-arg JWT_EXPIRATION=${{ secrets.JWT_EXPIRATION }} \
            -t ${{ steps.vars.outputs.dockerhub_image }}:latest \
            -t ${{ steps.vars.outputs.dockerhub_image }}:${{ steps.vars.outputs.sha_tag }} \
            -t ${{ steps.vars.outputs.ghcr_image }}:latest \
            -t ${{ steps.vars.outputs.ghcr_image }}:${{ steps.vars.outputs.sha_tag }} .

      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Login to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Push Docker image to both registries
      - name: Push Docker image
        run: |
          docker push ${{ steps.vars.outputs.dockerhub_image }}:latest
          docker push ${{ steps.vars.outputs.dockerhub_image }}:${{ steps.vars.outputs.sha_tag }}
          docker push ${{ steps.vars.outputs.ghcr_image }}:latest
          docker push ${{ steps.vars.outputs.ghcr_image }}:${{ steps.vars.outputs.sha_tag }}
