name: Build Spring Boot App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${{ secrets.POSTGRES_DB }}
  SPRING_DATASOURCE_USERNAME: ${{ secrets.POSTGRES_USER }}
  SPRING_DATASOURCE_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}

jobs:
  build-wsl:
    name: Build JAR for WSL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Build JAR
        run: mvn clean package -DskipTests

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: tasklist-jar
          path: target/*.jar

  build-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: build-wsl
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/tasklist:latest
          build-args: |
            SPRING_DATASOURCE_URL=${{ env.SPRING_DATASOURCE_URL }}
            SPRING_DATASOURCE_USERNAME=${{ env.SPRING_DATASOURCE_USERNAME }}
            SPRING_DATASOURCE_PASSWORD=${{ env.SPRING_DATASOURCE_PASSWORD }}
            JWT_SECRET=${{ env.JWT_SECRET }}
            JWT_EXPIRATION=${{ env.JWT_EXPIRATION }}

